### ISSUE TITLE
To add languages to support

### ISSUE THREAD

**Issue by OlivierJourdan** [LabVIEWCommunityTraining/cti-documentation#2]
What languages do we want to support (and have translators) as a first step?

- English
- Spanish
- French

When the list is defined, I'll add the code to support all of them.

**Comment by enoearias** [comment]
Hi @OlivierJourdan, please add Chinese.
thanks!!!

**Comment by OlivierJourdan** [comment]
The source now includes 4 languages: English, Spanish, French, and Chinese.
